In [1]:
import sys

sys.path.append('../..')

In [2]:
from ccp.accounts import Accounts, DFAccounts
from ccp.states import MembersState

In [3]:
states = MembersState(4)

In [4]:
print states.alive_states
print states.size

states.die(3)
print states.alive_states

states.die(3)
print states.alive_states

states.resurrect_all()

[ True  True  True  True]
4
[ True  True  True False]
[ True  True  True False]


In [5]:
accounts = Accounts(states, 5)
df_accounts = DFAccounts(states, 5)

In [6]:
accounts.amounts[2] = 3
accounts.amounts

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
accounts.put_amounts(2, 3)
accounts.amounts

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [8]:
states.die(3)
accounts.put_amounts(3, 100)
accounts.amounts

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [9]:
accounts.put_amounts(0, 100)
accounts.put_amounts(1, 200)

In [10]:
accounts.amounts

array([[ 100.,  100.,  100.,  100.,  100.],
       [ 200.,  200.,  200.,  200.,  200.],
       [   3.,    3.,    3.,    3.,    3.],
       [   0.,    0.,    0.,    0.,    0.]])

In [11]:
df_accounts.put_amounts(0, 120)
df_accounts.put_amounts(3, 100)
print df_accounts.amounts

[[ 120.  120.  120.  120.  120.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.]]


In [12]:
states.resurrect_all()

In [13]:
accounts.amounts

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
df_accounts.amounts

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
df_accounts.put_amounts(0, 0.)
df_accounts.put_amounts(1, 1000) #will be capoute!
df_accounts.put_amounts(2, 100)
df_accounts.put_amounts(3, 50)

print df_accounts.amounts
states.die(1)
print df_accounts.states.alive_states.reshape((4,1))
print

print df_accounts.total_default_fund()
print df_accounts.total_default_fund(only_surviving=False)

[[    0.     0.     0.     0.     0.]
 [ 1000.  1000.  1000.  1000.  1000.]
 [  100.   100.   100.   100.   100.]
 [   50.    50.    50.    50.    50.]]
[[ True]
 [False]
 [ True]
 [ True]]

[ 150.  150.  150.  150.  150.]
[ 1150.  1150.  1150.  1150.  1150.]


In [16]:
mean = df_accounts.mean_contribution()
print mean

print mean.sum()

[ 50.  50.  50.  50.  50.]
250.0
